name = "linmusic"
compatibility_date = "2026-01-14"
pages_build_output_dir = "./dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "linmusic"
database_id = "bf7fb6d7-3081-452f-bca7-3ad164eb0528" 
# 开发环境配置
[dev]
port = 8788
